/* Auto-generated by genmsg_cpp for file /home/mdesnoyer/src/reefbot/ros/reefbot_msgs/msg/ImageCaptured.msg */
#ifndef REEFBOT_MSGS_MESSAGE_IMAGECAPTURED_H
#define REEFBOT_MSGS_MESSAGE_IMAGECAPTURED_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "sensor_msgs/Image.h"

namespace reefbot_msgs
{
template <class ContainerAllocator>
struct ImageCaptured_ {
  typedef ImageCaptured_<ContainerAllocator> Type;

  ImageCaptured_()
  : header()
  , image_id(0)
  , image()
  {
  }

  ImageCaptured_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , image_id(0)
  , image(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef uint64_t _image_id_type;
  uint64_t image_id;

  typedef  ::sensor_msgs::Image_<ContainerAllocator>  _image_type;
   ::sensor_msgs::Image_<ContainerAllocator>  image;


  typedef boost::shared_ptr< ::reefbot_msgs::ImageCaptured_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::reefbot_msgs::ImageCaptured_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ImageCaptured
typedef  ::reefbot_msgs::ImageCaptured_<std::allocator<void> > ImageCaptured;

typedef boost::shared_ptr< ::reefbot_msgs::ImageCaptured> ImageCapturedPtr;
typedef boost::shared_ptr< ::reefbot_msgs::ImageCaptured const> ImageCapturedConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::reefbot_msgs::ImageCaptured_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::reefbot_msgs::ImageCaptured_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace reefbot_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::reefbot_msgs::ImageCaptured_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::reefbot_msgs::ImageCaptured_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::reefbot_msgs::ImageCaptured_<ContainerAllocator> > {
  static const char* value() 
  {
    return "2a14011e5d0ce053cbc95beb961ecdae";
  }

  static const char* value(const  ::reefbot_msgs::ImageCaptured_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x2a14011e5d0ce053ULL;
  static const uint64_t static_value2 = 0xcbc95beb961ecdaeULL;
};

template<class ContainerAllocator>
struct DataType< ::reefbot_msgs::ImageCaptured_<ContainerAllocator> > {
  static const char* value() 
  {
    return "reefbot_msgs/ImageCaptured";
  }

  static const char* value(const  ::reefbot_msgs::ImageCaptured_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::reefbot_msgs::ImageCaptured_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# This message specifies that a still image was captured by the system.\n\
#\n\
# If you're using OpenCV to handle images, look up the cv_bridge in \n\
# ROS to easily write/read this message.\n\
#\n\
# Author: Mark Desnoyer (markd@cmu.edu)\n\
# Date: Sept 2010\n\
\n\
Header header\n\
\n\
# Optional Id to identify the image\n\
uint64 image_id\n\
\n\
# Full color image that was captured\n\
sensor_msgs/Image image\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Image\n\
# This message contains an uncompressed image\n\
# (0, 0) is at top-left corner of image\n\
#\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of cameara\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
                     # If the frame_id here and the frame_id of the CameraInfo\n\
                     # message associated with the image conflict\n\
                     # the behavior is undefined\n\
\n\
uint32 height         # image height, that is, number of rows\n\
uint32 width          # image width, that is, number of columns\n\
\n\
# The legal values for encoding are in file src/image_encodings.cpp\n\
# If you want to standardize a new string format, join\n\
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n\
\n\
string encoding       # Encoding of pixels -- channel meaning, ordering, size\n\
                      # taken from the list of strings in src/image_encodings.cpp\n\
\n\
uint8 is_bigendian    # is this data bigendian?\n\
uint32 step           # Full row length in bytes\n\
uint8[] data          # actual matrix data, size is (step * rows)\n\
\n\
";
  }

  static const char* value(const  ::reefbot_msgs::ImageCaptured_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::reefbot_msgs::ImageCaptured_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::reefbot_msgs::ImageCaptured_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::reefbot_msgs::ImageCaptured_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.image_id);
    stream.next(m.image);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ImageCaptured_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::reefbot_msgs::ImageCaptured_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::reefbot_msgs::ImageCaptured_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "image_id: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.image_id);
    s << indent << "image: ";
s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.image);
  }
};


} // namespace message_operations
} // namespace ros

#endif // REEFBOT_MSGS_MESSAGE_IMAGECAPTURED_H

