/* Auto-generated by genmsg_cpp for file /home/mdesnoyer/src/reefbot/ros/objdetect_msgs/msg/Mask.msg */
#ifndef OBJDETECT_MSGS_MESSAGE_MASK_H
#define OBJDETECT_MSGS_MESSAGE_MASK_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "sensor_msgs/RegionOfInterest.h"
#include "sensor_msgs/Image.h"

namespace objdetect_msgs
{
template <class ContainerAllocator>
struct Mask_ {
  typedef Mask_<ContainerAllocator> Type;

  Mask_()
  : roi()
  , mask()
  {
  }

  Mask_(const ContainerAllocator& _alloc)
  : roi(_alloc)
  , mask(_alloc)
  {
  }

  typedef  ::sensor_msgs::RegionOfInterest_<ContainerAllocator>  _roi_type;
   ::sensor_msgs::RegionOfInterest_<ContainerAllocator>  roi;

  typedef  ::sensor_msgs::Image_<ContainerAllocator>  _mask_type;
   ::sensor_msgs::Image_<ContainerAllocator>  mask;


  typedef boost::shared_ptr< ::objdetect_msgs::Mask_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::objdetect_msgs::Mask_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Mask
typedef  ::objdetect_msgs::Mask_<std::allocator<void> > Mask;

typedef boost::shared_ptr< ::objdetect_msgs::Mask> MaskPtr;
typedef boost::shared_ptr< ::objdetect_msgs::Mask const> MaskConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::objdetect_msgs::Mask_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::objdetect_msgs::Mask_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace objdetect_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::objdetect_msgs::Mask_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::objdetect_msgs::Mask_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::objdetect_msgs::Mask_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ecbf10b456dc7d2982ac745b3ea8ef9c";
  }

  static const char* value(const  ::objdetect_msgs::Mask_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xecbf10b456dc7d29ULL;
  static const uint64_t static_value2 = 0x82ac745b3ea8ef9cULL;
};

template<class ContainerAllocator>
struct DataType< ::objdetect_msgs::Mask_<ContainerAllocator> > {
  static const char* value() 
  {
    return "objdetect_msgs/Mask";
  }

  static const char* value(const  ::objdetect_msgs::Mask_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::objdetect_msgs::Mask_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# this message is used to mark where an object is present in an image\n\
# this can be done either by a roi region on the image (less precise)\n\
# or a mask (more precise)\n\
\n\
sensor_msgs/RegionOfInterest roi\n\
\n\
# in the case when mask is used, 'roi' specifies the image region and 'mask'\n\
# (which should be of the same size) a binary mask in that region\n\
sensor_msgs/Image mask\n\
================================================================================\n\
MSG: sensor_msgs/RegionOfInterest\n\
# This message is used to specify a region of interest within an image.\n\
#\n\
# When used to specify the ROI setting of the camera when the image was\n\
# taken, the height and width fields should either match the height and\n\
# width fields for the associated image; or height = width = 0\n\
# indicates that the full resolution image was captured.\n\
\n\
uint32 x_offset  # Leftmost pixel of the ROI\n\
                 # (0 if the ROI includes the left edge of the image)\n\
uint32 y_offset  # Topmost pixel of the ROI\n\
                 # (0 if the ROI includes the top edge of the image)\n\
uint32 height    # Height of ROI\n\
uint32 width     # Width of ROI\n\
\n\
# True if a distinct rectified ROI should be calculated from the \"raw\"\n\
# ROI in this message. Typically this should be False if the full image\n\
# is captured (ROI not used), and True if a subwindow is captured (ROI\n\
# used).\n\
bool do_rectify\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Image\n\
# This message contains an uncompressed image\n\
# (0, 0) is at top-left corner of image\n\
#\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of cameara\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
                     # If the frame_id here and the frame_id of the CameraInfo\n\
                     # message associated with the image conflict\n\
                     # the behavior is undefined\n\
\n\
uint32 height         # image height, that is, number of rows\n\
uint32 width          # image width, that is, number of columns\n\
\n\
# The legal values for encoding are in file src/image_encodings.cpp\n\
# If you want to standardize a new string format, join\n\
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n\
\n\
string encoding       # Encoding of pixels -- channel meaning, ordering, size\n\
                      # taken from the list of strings in src/image_encodings.cpp\n\
\n\
uint8 is_bigendian    # is this data bigendian?\n\
uint32 step           # Full row length in bytes\n\
uint8[] data          # actual matrix data, size is (step * rows)\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::objdetect_msgs::Mask_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::objdetect_msgs::Mask_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.roi);
    stream.next(m.mask);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Mask_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::objdetect_msgs::Mask_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::objdetect_msgs::Mask_<ContainerAllocator> & v) 
  {
    s << indent << "roi: ";
s << std::endl;
    Printer< ::sensor_msgs::RegionOfInterest_<ContainerAllocator> >::stream(s, indent + "  ", v.roi);
    s << indent << "mask: ";
s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.mask);
  }
};


} // namespace message_operations
} // namespace ros

#endif // OBJDETECT_MSGS_MESSAGE_MASK_H

