(cl:in-package reefbot_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          LEFT_SPEED-VAL
          LEFT_SPEED
          RIGHT_SPEED-VAL
          RIGHT_SPEED
          VERTICAL_SPEED-VAL
          VERTICAL_SPEED
          DEPTH-VAL
          DEPTH
          HEADING-VAL
          HEADING
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          INTERNAL_HUMIDITY-VAL
          INTERNAL_HUMIDITY
          WATER_TEMP-VAL
          WATER_TEMP
          SPIN_COUNT-VAL
          SPIN_COUNT
          INTERNAL_TEMP-VAL
          INTERNAL_TEMP
          TOTAL_POWER-VAL
          TOTAL_POWER
          VOLTAGE_DROP-VAL
          VOLTAGE_DROP
          TETHER_VOLTAGE-VAL
          TETHER_VOLTAGE
          BUS_VOLTAGE-VAL
          BUS_VOLTAGE
          BUS_CURRENT-VAL
          BUS_CURRENT
          COMM_ERROR_COUNT-VAL
          COMM_ERROR_COUNT
))