(cl:defpackage objdetect_msgs-srv
  (:use )
  (:export
   "DETECTOBJECTGRIDSERVICE"
   "<DETECTOBJECTGRIDSERVICE-REQUEST>"
   "DETECTOBJECTGRIDSERVICE-REQUEST"
   "<DETECTOBJECTGRIDSERVICE-RESPONSE>"
   "DETECTOBJECTGRIDSERVICE-RESPONSE"
   "DETECTOBJECTSERVICE"
   "<DETECTOBJECTSERVICE-REQUEST>"
   "DETECTOBJECTSERVICE-REQUEST"
   "<DETECTOBJECTSERVICE-RESPONSE>"
   "DETECTOBJECTSERVICE-RESPONSE"
  ))

